FROM tutum/apache-php:latest
MAINTAINER Matt Day

ADD index.php /app/index.php
ADD piealicious.png /app/piealicious.png
ADD banner-1.jpg /app/banner-1.jpg
ADD banner-2.jpg /app/banner-2.jpg
ADD time.jpg /app/time.jpg
ADD mince-pies.jpg /app/mince-pies.jpg
ADD image_slide.js /app/image_slide.js
ADD jquery.min.js /app/jquery.min.js
ADD style.css /app/style.css
ADD background.jpg /app/background.jpg
ADD transparent.png /app/transparent.png
ADD logo.png /app/logo.png

EXPOSE 80
WORKDIR /app
CMD ["/run.sh"]
